### ISSUE TITLE
Testing finetuned model

### ISSUE THREAD

**Issue by nmeegan** [saqib736/Depth_Estimation#2]
Hello! Thank you for your great work!

I am trying to run inference on a finetuned Marigold model using Marigold's run.py script and supplying the checkpoint name as an argument. However, when I do so I get an error message that I am missing the model_index.json file. Below I show the output checkpoint from running the training script along with the error message. Is there any way to produce this file or is there another way to get Marigold to load from my local checkpoint? Thank you again!

![image](https://github.com/saqib736/Depth_Estimation/assets/74822467/b835365c-4362-4e19-9ab8-2e68bfcd0f0f)
![image](https://github.com/saqib736/Depth_Estimation/assets/74822467/f05952a3-4d0a-4a8b-9b68-60b4ea5661d4)
![image](https://github.com/saqib736/Depth_Estimation/assets/74822467/add9396c-d31d-4e17-a2db-a42793358b06)

**Comment by saqib736** [comment]
> Hello! Thank you for your great work!
> 
> 
> 
> I am trying to run inference on a finetuned Marigold model using Marigold's run.py script and supplying the checkpoint name as an argument. However, when I do so I get an error message that I am missing the model_index.json file. Below I show the output checkpoint from running the training script along with the error message. Is there any way to produce this file or is there another way to get Marigold to load from my local checkpoint? Thank you again!
> 
> 
> 
> ![image](https://github.com/saqib736/Depth_Estimation/assets/74822467/b835365c-4362-4e19-9ab8-2e68bfcd0f0f)
> 
> ![image](https://github.com/saqib736/Depth_Estimation/assets/74822467/f05952a3-4d0a-4a8b-9b68-60b4ea5661d4)
> 
> ![image](https://github.com/saqib736/Depth_Estimation/assets/74822467/add9396c-d31d-4e17-a2db-a42793358b06)
> 
> 
> 
> 
> 
> 
> 
> 

I haven't tried the inference, as i am busy with some other things. But I will look into this.

**Comment by nmeegan** [comment]
I haven't had a chance to test yet, but according to Marigold's repository (now that the official training code has been released) it seems that replacing the unet folder is the way to perform inference. Thank you again for your great work!

**Comment by billie2jean** [comment]
> I haven't had a chance to test yet, but according to Marigold's repository (now that the official training code has been released) it seems that replacing the unet folder is the way to perform inference. Thank you again for your great work!

I find that there's a `bin` file in marigold-v1-0 folder, but i dont know how to produce it.

**Comment by nmeegan** [comment]
> > I haven't had a chance to test yet, but according to Marigold's repository (now that the official training code has been released) it seems that replacing the unet folder is the way to perform inference. Thank you again for your great work!
> 
> I find that there's a `bin` file in marigold-v1-0 folder, but i dont know how to produce it.

Going to test it today, I will let you know how it goes!

**Comment by nmeegan** [comment]
Hi @billie2jean, I found that by downloading the Marigold checkpoint from [here](https://huggingface.co/prs-eth/marigold-lcm-v1-0/tree/main), then replacing the config.json and diffusion_pytorch_model.safetensors in the unet/ folder produces the results from my finetuned model when following Marigold's inference code. Let me know if you have any issues or questions!

**Comment by billie2jean** [comment]
Why dont replace the diffusion_pytorch_model.bin?  Or just use the provided diffusion_pytorch_model.bin? this is one Q.
I use this code [https://github.com/saqib736/Depth_Estimation](url) dont produce a file like diffusion_pytorch_model.bin, this is other Q. 
So sorry for bother you, and  I'm so ignorant.

**Comment by billie2jean** [comment]
> Hi @billie2jean, I found that by downloading the Marigold checkpoint from [here](https://huggingface.co/prs-eth/marigold-lcm-v1-0/tree/main), then replacing the config.json and diffusion_pytorch_model.safetensors in the unet/ folder produces the results from my finetuned model when following Marigold's inference code. Let me know if you have any issues or questions!

Hi, I just find that the Marigold can run without diffusion_pytorch_bin, but actually, shouldn't the BIN file store the parameters of the model? And these parameters will be read during model training.

**Comment by saqib736** [comment]
I have updated the stable diffusion directory, now it contains both training and inference code.
