### ISSUE TITLE
missing file for training

### ISSUE THREAD

**Issue by YacineDeghaies** [saqib736/Depth_Estimation#3]
After setting the path to my dataset I run ./train.sh and I get this error:

can't open file '/vol/fob-vol3/mi20/deghaisa/code/Depth_Estimation/stable_difusion/depth2image_trainer.py': [Errno 2] No such file or directory

**Comment by saqib736** [comment]
> After setting the path to my dataset I run ./train.sh and I get this error:
> 
> can't open file '/vol/fob-vol3/mi20/deghaisa/code/Depth_Estimation/stable_difusion/depth2image_trainer.py': [Errno 2] No such file or directory

Sorry I was busy with my master's thesis, I will update the repo with the latest code and scripts.
